import * as T from './three.module.js';
const $=s=>document.querySelector(s), scene=new T.Scene();scene.background=new T.Color('#b5c9ce');scene.fog=new T.Fog('#b5c9ce',100,390);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;$('#world').append(renderer.domElement);
const camera=new T.PerspectiveCamera(65,innerWidth/innerHeight,.1,700);camera.rotation.order='YXZ';scene.add(new T.HemisphereLight(0xd5e5ee,0x806e55,2.3));const sun=new T.DirectionalLight(0xffedcc,3);sun.position.set(-60,110,60);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-185,right:185,top:150,bottom:-150,far:350});sun.shadow.bias=-.0006;scene.add(sun);
const origin=[-75.15285,39.94305],c=Math.cos(.17),s=Math.sin(.17);function project([lng,lat]){let x=(lng-origin[0])*85320,z=-(lat-origin[1])*111320;return new T.Vector2(x*c-z*s,x*s+z*c)}
function texture(wood=false){const cv=document.createElement('canvas');cv.width=cv.height=256;const ctx=cv.getContext('2d');ctx.fillStyle=wood?'#827462':'#b09a82';ctx.fillRect(0,0,256,256);let seed=7;const rand=()=>((seed=seed*16807%2147483647)/2147483647);for(let y=0;y<256;y+=wood?25:16)for(let x=-32;x<256;x+=wood?300:64){let k=rand();ctx.fillStyle=wood?`rgb(${120+k*25},${107+k*22},${89+k*20})`:`rgb(${132+k*42},${68+k*28},${48+k*22})`;ctx.fillRect(x+(wood?0:(y/16%2)*32)+1,y+1,wood?298:62,wood?23:14)}const t=new T.CanvasTexture(cv);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(1.8,1.8);t.colorSpace=T.SRGBColorSpace;return t}
const brick=new T.MeshStandardMaterial({map:texture(),roughness:.95}),wood=new T.MeshStandardMaterial({map:texture(true),roughness:1}),unknown=new T.MeshStandardMaterial({color:0x8a8980}),roof=new T.MeshStandardMaterial({color:0x454b49,roughness:1,side:T.DoubleSide}),glass=new T.MeshStandardMaterial({color:0x34494b,roughness:.36}),trim=new T.MeshStandardMaterial({color:0xd5c9aa}),shutter=new T.MeshStandardMaterial({color:0x384e49}),door=new T.MeshStandardMaterial({color:0x354642}),stone=new T.MeshStandardMaterial({color:0x928d7e,roughness:1});
const buckets=new Map();function box(mat,x,y,z,w,h,d,angle=0){if(!buckets.has(mat))buckets.set(mat,[]);const o=new T.Object3D();o.position.set(x,y,z);o.scale.set(w,h,d);o.rotation.y=angle;o.updateMatrix();buckets.get(mat).push(o.matrix.clone())}
const ground=new T.Mesh(new T.PlaneGeometry(850,850),new T.MeshStandardMaterial({color:0x8b8370,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const buildings=[],wallMeshes=[];let overhead=false,yaw=0,pitch=0;const keys={};let drag=false,last=[0,0];
function inside(x,z,pts){let hit=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){let a=pts[i],b=pts[j];if((a.y>z)!=(b.y>z)&&x<(b.x-a.x)*(z-a.y)/(b.y-a.y)+a.x)hit=!hit}return hit}
function blocked(x,z,exclude){return buildings.some(b=>b!==exclude&&x>=b.minX-.3&&x<=b.maxX+.3&&z>=b.minZ-.3&&z<=b.maxZ+.3&&inside(x,z,b.pts))}
try{
const data=await(await fetch('./buildings.geojson')).json();for(const f of data.features)for(const poly of f.geometry.coordinates){const pts=poly[0].slice(0,-1).map(project),p=f.properties;buildings.push({pts,p,h:p.height*.3048,minX:Math.min(...pts.map(v=>v.x)),maxX:Math.max(...pts.map(v=>v.x)),minZ:Math.min(...pts.map(v=>v.y)),maxZ:Math.max(...pts.map(v=>v.y))})}
for(const b of buildings){const {pts,p,h}=b,shape=new T.Shape(pts.map(v=>new T.Vector2(v.x,-v.y))),g=new T.ExtrudeGeometry(shape,{depth:h,bevelEnabled:false});g.rotateX(-Math.PI/2);const mesh=new T.Mesh(g,p.material==='wood'?wood:p.material==='brick'?brick:unknown);mesh.castShadow=mesh.receiveShadow=true;mesh.userData.building=b;scene.add(mesh);wallMeshes.push(mesh);
const cx=(b.minX+b.maxX)/2,cz=(b.minZ+b.maxZ)/2,w=b.maxX-b.minX,d=b.maxZ-b.minZ;
// Provisional pitched roof, clipped to the actual footprint on each side of the ridge.
if(p.type!=='wall'){let acrossX=w<d,mid=acrossX?cx:cz,span=acrossX?w:d,rise=Math.min(span*.4,3),positions=[];
for(let side of [-1,1]){let clipped=[];for(let i=0;i<pts.length;i++){let a=pts[i],q=pts[(i+1)%pts.length],av=(acrossX?a.x:a.y)-mid,bv=(acrossX?q.x:q.y)-mid;if(av*side>=0)clipped.push(a.clone());if(av*bv<0){let t=av/(av-bv);clipped.push(a.clone().lerp(q,t))}}if(clipped.length>=3){let triangles=T.ShapeUtils.triangulateShape(clipped,[]);for(let tri of triangles)for(let j of tri){let v=clipped[j],k=acrossX?v.x:v.y;positions.push(v.x,h+rise*Math.max(0,1-Math.abs(k-mid)/(span/2)),v.y)}}}
const rg=new T.BufferGeometry();rg.setAttribute('position',new T.Float32BufferAttribute(positions,3));rg.computeVertexNormals();let cap=new T.Mesh(rg,roof);cap.castShadow=true;scene.add(cap);
// Close the gable ends with wall-colored triangles.
const end=[];for(let i=0;i<pts.length;i++){let a=pts[i],q=pts[(i+1)%pts.length];let av=(acrossX?a.x:a.y)-mid,bv=(acrossX?q.x:q.y)-mid;let chain=[a];if(av*bv<0)chain.push(a.clone().lerp(q,av/(av-bv)));chain.push(q);for(let j=0;j<chain.length-1;j++){let v=chain[j],u=chain[j+1],vh=h+rise*Math.max(0,1-Math.abs((acrossX?v.x:v.y)-mid)/(span/2)),uh=h+rise*Math.max(0,1-Math.abs((acrossX?u.x:u.y)-mid)/(span/2));end.push(v.x,h,v.y,u.x,h,u.y,v.x,vh,v.y,u.x,h,u.y,u.x,uh,u.y,v.x,vh,v.y)}}let eg=new T.BufferGeometry();eg.setAttribute('position',new T.Float32BufferAttribute(end,3));eg.computeVertexNormals();scene.add(new T.Mesh(eg,p.material==='wood'?wood:brick));if(w>3&&d>4)box(brick,cx+w*.28,h+rise*.65,cz+d*.2,.7,1.8,.85)}
if(p.type==='wall')continue;
let area=0;for(let i=0;i<pts.length;i++){let a=pts[i],q=pts[(i+1)%pts.length];area+=a.x*q.y-q.x*a.y}
let entrance=false;for(let i=0;i<pts.length;i++){const a=pts[i],q=pts[(i+1)%pts.length],dx=q.x-a.x,dz=q.y-a.y,len=Math.hypot(dx,dz);if(len<2.4)continue;const ux=dx/len,uz=dz/len,sign=area>0?1:-1,nx=uz*sign,nz=-ux*sign,mx=(a.x+q.x)/2,mz=(a.y+q.y)/2;if(blocked(mx+nx*.7,mz+nz*.7,b))continue;const angle=Math.atan2(-uz,ux),n=Math.max(1,Math.floor(len/2.5)),floors=Math.max(1,Math.round(p.height/12));
const put=(mat,t,y,ww,hh,dd,off=.06)=>box(mat,a.x+ux*t+nx*off,y,a.y+uz*t+nz*off,ww,hh,dd,angle);
for(let j=0;j<n;j++){let t=len*(j+.5)/n;if(blocked(a.x+ux*t+nx*.8,a.y+uz*t+nz*.8,b))continue;for(let f=0;f<floors;f++){let yy=f*3.6576+2.0,wh=f===floors-1?1.32:1.65,ww=Math.min(1.0,len/n*.5);const isDoor=f===0&&j===0&&len<15;const shop=f===0&&p.type.includes('store')&&!isDoor;if(isDoor){put(trim,t,1.45,1.25,2.7,.18);put(door,t,1.35,1,2.45,.2,.18);put(glass,t,2.55,.9,.3,.22,.19);put(stone,t,.15,1.45,.3,.9,.4);entrance=true;continue}if(shop){ww=Math.min(1.7,len/n*.8);wh=2.2;yy=1.8}put(trim,t,yy,ww+.2,wh+.18,.13);put(glass,t,yy,ww,wh,.17,.13);put(trim,t,yy,.045,wh,.2,.19);put(trim,t,yy,ww,.045,.2,.19);if(!shop){put(shutter,t-ww*.78,yy,ww*.43,wh,.15);put(shutter,t+ww*.78,yy,ww*.43,wh,.15)}}}put(trim,len/2,h-.16,len,.23,.3);}
}
for(const [mat,matrices] of buckets){const inst=new T.InstancedMesh(new T.BoxGeometry(1,1,1),mat,matrices.length);matrices.forEach((m,i)=>inst.setMatrixAt(i,m));inst.castShadow=inst.receiveShadow=true;scene.add(inst)}
function reset(){overhead=false;$('#overview').textContent='View from above';const v=project([-75.1528,39.94302]);camera.position.set(v.x,1.7,v.y);if(blocked(v.x,v.y)){for(let z=-20;z<30;z+=1){if(!blocked(v.x,z)){camera.position.z=z;break}}}yaw=-Math.PI/2;pitch=0;camera.rotation.set(pitch,yaw,0);$('#location').textContent='Lombard Street';}
reset();$('#loading').remove();$('#reset').onclick=reset;$('#overview').onclick=()=>{overhead=!overhead;if(overhead){camera.position.set(10,230,120);camera.lookAt(0,0,0);$('#overview').textContent='Back to street';$('#location').textContent='Neighborhood overview'}else reset()};
$('#walk').onclick=()=>{if(overhead)reset();renderer.domElement.requestPointerLock?.()};document.addEventListener('pointerlockchange',()=>{$('#walk').textContent=document.pointerLockElement?'Esc to release':'Walk here'});$('#about').onclick=()=>{$('#info').hidden=!$('#info').hidden};$('#close').onclick=()=>$('#info').hidden=true;
renderer.domElement.addEventListener('pointerdown',e=>{drag=true;last=[e.clientX,e.clientY];renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointerup',()=>drag=false);document.addEventListener('pointermove',e=>{if(overhead)return;if(document.pointerLockElement||drag){let dx=document.pointerLockElement?e.movementX:e.clientX-last[0],dy=document.pointerLockElement?e.movementY:e.clientY-last[1];yaw-=dx*.003;pitch=Math.max(-1.2,Math.min(1.2,pitch-dy*.003));camera.rotation.set(pitch,yaw,0);last=[e.clientX,e.clientY]}});
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('blur',()=>{for(let k in keys)keys[k]=false;drag=false});document.querySelectorAll('[data-key]').forEach(el=>{el.onpointerdown=e=>{el.setPointerCapture(e.pointerId);keys[el.dataset.key]=true};el.onpointerup=el.onpointercancel=()=>keys[el.dataset.key]=false});
const map=$('#map'),ctx=map.getContext('2d'),ray=new T.Raycaster();let lastTime=performance.now(),tick=0;
function render(now){requestAnimationFrame(render);const dt=Math.min((now-lastTime)/1000,.04);lastTime=now;if(!overhead){let forward=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),side=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),speed=(keys.ShiftLeft?5:2.5)*dt/Math.max(1,Math.hypot(forward,side));let dx=(-Math.sin(yaw)*forward+Math.cos(yaw)*side)*speed,dz=(-Math.cos(yaw)*forward-Math.sin(yaw)*side)*speed;let x=camera.position.x,z=camera.position.z;if(Math.abs(x+dx)<200&&!blocked(x+dx+Math.sign(dx)*.3,z))camera.position.x+=dx;if(Math.abs(z+dz)<160&&!blocked(camera.position.x,z+dz+Math.sign(dz)*.3))camera.position.z+=dz;}
if(tick++%15===0){ray.setFromCamera(new T.Vector2(0,0),camera);const hit=ray.intersectObjects(wallMeshes)[0];let b=hit?.object.userData.building;$('#focus').hidden=!b||hit.distance>24||overhead;if(b&&hit.distance<24){$('#focus').textContent=(b.p.name||b.p.type+' · Building '+b.p.id)+' — '+b.p.height+' ft to roofline';}ctx.clearRect(0,0,200,150);for(const b of buildings){ctx.beginPath();b.pts.forEach((p,i)=>ctx[i?'lineTo':'moveTo'](100+p.x*.48,75+p.y*.48));ctx.closePath();ctx.fillStyle=b.p.material==='wood'?'#aa9973':'#d1b79b';ctx.fill()}ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(100+camera.position.x*.48,75+camera.position.z*.48,3,0,Math.PI*2);ctx.fill();}
renderer.render(scene,camera)}requestAnimationFrame(render);
// A small structured navigation tool for accessible agent-assisted exploration.
if(document.modelContext?.registerTool)document.modelContext.registerTool({name:'return_to_lombard',description:'Return the walking view to its starting point on Lombard Street.',inputSchema:{type:'object',properties:{}},execute:async()=>{reset();return {content:[{type:'text',text:'Returned to Lombard Street.'}]}}});
}catch(e){console.error(e);$('#loading').textContent='The neighborhood could not load. Please reload the page.'}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
